//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelperPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeHelperPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is the index day for the utility:.
        /// </summary>
        public static string AlertaIndexConsum {
            get {
                return ResourceManager.GetString("AlertaIndexConsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeHelper.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string chrShowFilter {
            get {
                return ResourceManager.GetString("chrShowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete?.
        /// </summary>
        public static string cntDeleteMbox {
            get {
                return ResourceManager.GetString("cntDeleteMbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string cntDeleteTitle {
            get {
                return ResourceManager.GetString("cntDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string cntNo {
            get {
                return ResourceManager.GetString("cntNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string cntYes {
            get {
                return ResourceManager.GetString("cntYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month consumption.
        /// </summary>
        public static string ConsumaLunaAnterioaraMesaj {
            get {
                return ResourceManager.GetString("ConsumaLunaAnterioaraMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string ConsumLstUtilitatiText {
            get {
                return ResourceManager.GetString("ConsumLstUtilitatiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month consumption.
        /// </summary>
        public static string ConsumLunaCurentaMesaj {
            get {
                return ResourceManager.GetString("ConsumLunaCurentaMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alert is not going to be active.
        /// </summary>
        public static string DataAlertaErrorValid {
            get {
                return ResourceManager.GetString("DataAlertaErrorValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this date there was added consumption.
        /// </summary>
        public static string DataConsumExistent {
            get {
                return ResourceManager.GetString("DataConsumExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data of this consumption is earlier than the initial index date.
        /// </summary>
        public static string DataConsumMicaDecatIndexInitial {
            get {
                return ResourceManager.GetString("DataConsumMicaDecatIndexInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date regarding the consumption range.
        /// </summary>
        public static string DataIndexInitialRespectareConsumInitial {
            get {
                return ResourceManager.GetString("DataIndexInitialRespectareConsumInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: This field is empty.
        /// </summary>
        public static string DenumireUtilitateCampGol {
            get {
                return ResourceManager.GetString("DenumireUtilitateCampGol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string enumFrecventeAlerteAnual {
            get {
                return ResourceManager.GetString("enumFrecventeAlerteAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without repeat.
        /// </summary>
        public static string enumFrecventeAlerteFaraRepetare {
            get {
                return ResourceManager.GetString("enumFrecventeAlerteFaraRepetare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string enumFrecventeAlerteLunar {
            get {
                return ResourceManager.GetString("enumFrecventeAlerteLunar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string enumFrecventeAlerteSaptamanal {
            get {
                return ResourceManager.GetString("enumFrecventeAlerteSaptamanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string enumFrecventeAlerteZilnic {
            get {
                return ResourceManager.GetString("enumFrecventeAlerteZilnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no consumption in the dates specified.
        /// </summary>
        public static string filtruDataInvalid {
            get {
                return ResourceManager.GetString("filtruDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter.
        /// </summary>
        public static string filtruInvalid {
            get {
                return ResourceManager.GetString("filtruInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The utility was not selected.
        /// </summary>
        public static string IdUtilitateErrorValid {
            get {
                return ResourceManager.GetString("IdUtilitateErrorValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Index:Invalid value.
        /// </summary>
        public static string IndexInitialValoareInvalida {
            get {
                return ResourceManager.GetString("IndexInitialValoareInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value in index.
        /// </summary>
        public static string IndexInvalid {
            get {
                return ResourceManager.GetString("IndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is greater than.
        /// </summary>
        public static string IndexMaiMareDecat {
            get {
                return ResourceManager.GetString("IndexMaiMareDecat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is less than.
        /// </summary>
        public static string IndexMaiMicDecat {
            get {
                return ResourceManager.GetString("IndexMaiMicDecat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is not in range.
        /// </summary>
        public static string IndexUtilitateInvalidInterval {
            get {
                return ResourceManager.GetString("IndexUtilitateInvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The are no records added.
        /// </summary>
        public static string InregistrariGoaleText {
            get {
                return ResourceManager.GetString("InregistrariGoaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string lblAlerteText {
            get {
                return ResourceManager.GetString("lblAlerteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string lblConsumText {
            get {
                return ResourceManager.GetString("lblConsumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Date.
        /// </summary>
        public static string lblDataAlertaText {
            get {
                return ResourceManager.GetString("lblDataAlertaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Date.
        /// </summary>
        public static string lblDataConsumText {
            get {
                return ResourceManager.GetString("lblDataConsumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Index Date.
        /// </summary>
        public static string lblDataIndexInitialText {
            get {
                return ResourceManager.GetString("lblDataIndexInitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDataText {
            get {
                return ResourceManager.GetString("lblDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert frequency.
        /// </summary>
        public static string lblFrecventaAlertaText {
            get {
                return ResourceManager.GetString("lblFrecventaAlertaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string lblFromText {
            get {
                return ResourceManager.GetString("lblFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string lblIndexText {
            get {
                return ResourceManager.GetString("lblIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblToText {
            get {
                return ResourceManager.GetString("lblToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement.
        /// </summary>
        public static string lblUnitateDeMasuraText {
            get {
                return ResourceManager.GetString("lblUnitateDeMasuraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string lblUtitlitatiText {
            get {
                return ResourceManager.GetString("lblUtitlitatiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial value.
        /// </summary>
        public static string lblValoareInitialaText {
            get {
                return ResourceManager.GetString("lblValoareInitialaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        public static string LunaAnterioara {
            get {
                return ResourceManager.GetString("LunaAnterioara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string LunaCurenta {
            get {
                return ResourceManager.GetString("LunaCurenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string mnuDelete {
            get {
                return ResourceManager.GetString("mnuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string mnuEdit {
            get {
                return ResourceManager.GetString("mnuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The are no records added.
        /// </summary>
        public static string NuSuntInregistrariAdaugate {
            get {
                return ResourceManager.GetString("NuSuntInregistrariAdaugate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The are no records added for the utility.
        /// </summary>
        public static string NuSuntInregistrariAdaugateUtilitatea {
            get {
                return ResourceManager.GetString("NuSuntInregistrariAdaugateUtilitatea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement:The field is empty.
        /// </summary>
        public static string UnitateMasuraCampGol {
            get {
                return ResourceManager.GetString("UnitateMasuraCampGol", resourceCulture);
            }
        }
    }
}
